import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from './components/header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{backgroundImage: `url('/background-2.jpg')`}} className="bg-cover">
      <body className={`${inter.className} backdrop-blur-xl min-h-screen h-full w-full`}>
        <div className="w-[96vw] lg:w-[50vw] mx-auto py-5">
          <Header></Header>
          {children}
        </div>
      </body>
    </html>
  );
}
